apiVersion: v1
kind: Service
metadata:
  name: pas-deploy
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.podLabels.app }}
  ports:
    - port: {{ .Values.service.targetPort }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP